object Versions {
    const val pluginAndroid = "8.0.0"
    const val pluginKotlin = "1.8.0"
    const val pluginHilt = "2.44"
    const val pluginJvm = "1.8.10"
    const val pluginSerialization = "1.8.10"
    const val pluginSafeArgs = ""

    const val androidXCore = "1.10.0"
    const val appCompat = "1.6.1"
    const val material = "1.8.0"
    const val contsraintLayout = "2.1.4"
    const val junit = "4.13.2"
    const val junitTest = "1.1.5"
    const val espresso = "3.5.1"

    const val navigation = "2.5.3"
    const val lifecycle = "2.6.1"
    const val room = "2.5.1"
    const val hilt = "2.44"
    const val coroutines = "1.6.4"

    const val glide = "4.15.1"
    const val timber = "5.0.1"
    const val retrofit = "2.9.0"
    const val retrofitKotlinxSerializaton = "1.0.0"
    const val chucker = "3.5.2"
    const val paging = "3.1.1"

    const val sqlcipher = "4.5.3"
    const val sqlite = "2.1.0"
    const val mockito = "5.3.1"
    const val archTesting = "2.2.0"
    const val coroutinesTest = "1.7.0-RC"
}